### ISSUE TITLE
Orientation does not change until I click on full screen button

### ISSUE THREAD

**Issue by skfaisal93** [MayurSolanki/AdaptiveStreamingExoplayer#3]
Hello,

The orientation of the screen does not change to horizontally when I rotate. However when I click on full screen button then it changed. Can you please fix this issue.

Thank you for such a wonderful project.

**Comment by MayurSolanki** [comment]
@skfaisal93  I have developed this project and open sourced it on consideration of core functionality only i.e player and streaming. you can achieve this by just handling orientation changed in device.
